import { Dino } from "@/types";

export function createEmptyDino(): Dino {
  return {
    id: 0,
    nom: '',
    hauteur: '',
    longueur: '',
    poids: '',
    region: '',
    periode_debut: '',
    periode_fin: '',
    cousins: [],
    especes_inf: [],
    regime: '',
    annee_decouv: '',
    etymologie: '',
    embranchement: '',
    sous_embranchement: '',
    super_classe: '',
    classe: '',
    sous_classe: '',
    infra_classe: '',
    super_ordre: '',
    ordre: '',
    sous_ordre: '',
    infra_ordre: '',
    micro_ordre: '',
    super_famille: '',
    famille: '',
    sous_famille: '',
    tribu: '',
    genre: '',
    clades: [],
    categorie: '',
    description: '',
    image: '',
    img_squelette: '',
  };
}

